// Lazy loader for the county-level native index generated by
// scripts/enrich-county.mjs. The index is split per state (one file per 2-digit
// state FIPS) so the browser only ever downloads the chunk for the location in
// play. Plant references are stored as integer indices into manifest.json (the
// catalog order), and names.json maps a 5-digit county FIPS to its county name.
//
// Everything is fetched on demand and cached at module scope, so repeated reads
// for the same state hit memory. Missing chunks (e.g. a state with no catalog
// natives, or before the national enrichment has run) resolve to empty rather
// than throwing.

// Vite turns this glob into a lazy import per matching file — exactly the
// per-state code-split we want. manifest.json / names.json ride along and are
// pulled the same way.
const files = import.meta.glob('../data/county-index/*.json')
// Per-state county SVG geometry (for the detail-page county map), loaded the
// same lazy, per-state way. See scripts/gen-county-paths.mjs.
const geoFiles = import.meta.glob('../data/countyPaths/*.json')

const cache = new Map() // filename stem -> Promise<data>
let usGeoPromise // national county geometry (loaded once)

function loadFile(stem) {
  if (!cache.has(stem)) {
    const importer = files[`../data/county-index/${stem}.json`]
    cache.set(stem, importer ? importer().then((m) => m.default) : Promise.resolve(null))
  }
  return cache.get(stem)
}

// USPS code -> 2-digit state FIPS (mirrors scripts/enrich-county.mjs).
export const USPS_FIP = {
  AL: '01', AK: '02', AZ: '04', AR: '05', CA: '06', CO: '08', CT: '09', DE: '10',
  DC: '11', FL: '12', GA: '13', HI: '15', ID: '16', IL: '17', IN: '18', IA: '19',
  KS: '20', KY: '21', LA: '22', ME: '23', MD: '24', MA: '25', MI: '26', MN: '27',
  MS: '28', MO: '29', MT: '30', NE: '31', NV: '32', NH: '33', NJ: '34', NM: '35',
  NY: '36', NC: '37', ND: '38', OH: '39', OK: '40', OR: '41', PA: '42', RI: '44',
  SC: '45', SD: '46', TN: '47', TX: '48', UT: '49', VT: '50', VA: '51', WA: '53',
  WV: '54', WI: '55', WY: '56',
}

const loadManifest = () => loadFile('manifest').then((m) => m?.ids || [])
const loadNames = () => loadFile('names').then((m) => m || {})
const loadState = (stateCode) => {
  const fip = USPS_FIP[stateCode]
  return fip ? loadFile(fip).then((m) => m || {}) : Promise.resolve({})
}

export function useCountyIndex() {
  // Counties (with display names) that have at least one native catalog plant in
  // the given state, sorted by name — for the picker and the county filter.
  async function countiesForState(stateCode) {
    const fip = USPS_FIP[stateCode]
    if (!fip) return []
    const [chunk, names] = await Promise.all([loadState(stateCode), loadNames()])
    return Object.keys(chunk)
      .map((cf) => ({ fips: fip + cf, name: names[fip + cf] || cf }))
      .sort((a, b) => a.name.localeCompare(b.name))
  }

  // Plant ids native to a single county (5-digit FIPS).
  async function plantIdsInCounty(fips) {
    const [chunk, ids] = await Promise.all([loadState(fipsState(fips)), loadManifest()])
    const cf = fips.slice(2)
    return (chunk[cf] || []).map((i) => ids[i]).filter(Boolean)
  }

  // Union of plant ids across several counties (e.g. a multiselect).
  async function plantIdsInCounties(fipsList) {
    const lists = await Promise.all(fipsList.map(plantIdsInCounty))
    return [...new Set(lists.flat())]
  }

  async function countyName(fips) {
    return (await loadNames())[fips] || null
  }

  // National county geometry for the main choropleth (one lazy, cached chunk).
  function usCountyGeometry() {
    return (usGeoPromise ||= import('../data/usCountyPaths.json').then((m) => m.default))
  }

  // Every county (5-digit FIPS) where the plant is native, across its native
  // states — the union used to shade the national map.
  async function plantCountiesNationwide(plant) {
    const sets = await Promise.all(
      (plant.nativeStates || []).map(async (s) => {
        const fip = USPS_FIP[s]
        if (!fip) return []
        const cf = await plantCountiesInState(plant.id, s)
        return [...cf].map((c) => fip + c)
      }),
    )
    return new Set(sets.flat())
  }

  // SVG geometry for a state's counties: { viewBox, paths: { countyFIP3: d } }.
  async function countyGeometry(stateCode) {
    const fip = USPS_FIP[stateCode]
    const importer = fip && geoFiles[`../data/countyPaths/${fip}.json`]
    return importer ? (await importer()).default : null
  }

  // The county FIP3s within a state where the given plant is native (for the
  // detail-page county map).
  async function plantCountiesInState(plantId, stateCode) {
    const [chunk, ids] = await Promise.all([loadState(stateCode), loadManifest()])
    const idx = ids.indexOf(plantId)
    if (idx < 0) return new Set()
    const out = new Set()
    for (const [cf, arr] of Object.entries(chunk)) if (arr.includes(idx)) out.add(cf)
    return out
  }

  return {
    countiesForState,
    plantIdsInCounty,
    plantIdsInCounties,
    countyName,
    countyGeometry,
    plantCountiesInState,
    usCountyGeometry,
    plantCountiesNationwide,
  }
}

// FIPS5 -> USPS, so a county can find its own state chunk.
const FIP_USPS = Object.fromEntries(Object.entries(USPS_FIP).map(([k, v]) => [v, k]))
const fipsState = (fips) => FIP_USPS[fips.slice(0, 2)]
